# switchblade previous theme: theme = "ashen"
theme = "switchblade-gruvbox-material-light" # switchblade managed
# Light themes: "iceberg-light"
# Dark themes: "ashen"

[editor]
rulers = [80]
line-number = "relative"

# [editor.cursor-shape]
# insert = "bar"

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
