[language-server.expert]
command = "/usr/local/bin/expert_darwin_arm64 --stdio"

[[language]]
name="elixir"

[[language]]
name="javascript"

# Deno Language Server
[language-server.deno]
command = "deno"
args = ["lsp"]

# (NODE) Javascript
[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

# (DENO) Javascript
[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["js", "jsx"]
auto-format = true
language-servers = ["deno-lsp"]

# (NODE) Typescript
[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

# (DENO) Typescript
[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["ts", "tsx"]
auto-format = true
language-servers = ["deno-lsp"]

# Python
[[language]]
name = "python"
language-servers = ["pyright"]

# For TailwindCSS
[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true
